### ISSUE TITLE
Incompatibility with easy_gantt on RM 3.2.0

### ISSUE THREAD

**Issue by tjaeger** [AlphaNodes/redmine_tweaks#26]
Hi, i found that i couldn't install the easy_gantt plugin while redmine_tweaks is installed.
Now i can't find a root cause really, but maybe the snippet below gives a clue. I have to start somewhere to investigate :)

> snip<
> bundle exec rake redmine:plugins:migrate RAILS_ENV=production
> `
> ** Execute environment
> rake aborted!
> NoMethodError: undefined method`=~' for #
> /home/user/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `block (3 levels) in '
> /home/user/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in`reject!'
> /home/user/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `block (2 levels) in '
> `

**Comment by alexandermeindl** [comment]
I do not have this plugin, which is why I cannot work on a solution.

**Comment by alexandermeindl** [comment]
See https://github.com/AlphaNodes/redmine_tweaks/issues/32#issuecomment-241020256, it is the same problem.

**Comment by alexandermeindl** [comment]
Should work with latest deface gem.
