### ISSUE TITLE
Add file: link ?

### ISSUE THREAD

**Issue by LuisSerrano** [AlphaNodes/redmine_tweaks#31]
It is possible enable the link to files (external link to files in shared folders)?

Thanks

**Comment by alexandermeindl** [comment]
If I understand it right, you mean to link to a Windows shared folder, right? There is a thread about it here: https://www.redmine.org/boards/1/topics/29216?r=29783#message-29783

Problem with this is, we can implement this as a macro, but it'll only work with modern browsers, if https://noscript.net/ plugins is installed (e.g. with Firefox). It is a security issue with linking to files, thats the reason, this does not work with modern browsers.
