### ISSUE TITLE
Prevent user to log time on closed issues

### ISSUE THREAD

**Issue by electricnachus** [AlphaNodes/redmine_tweaks#33]
Hi, can i prevent users to lot time with the plug in? if not, can i add a request for that?

Thanks!

**Comment by alexandermeindl** [comment]
I find thes feature good and I implemented it today :) For the reference, I found a discussion here about the same topic: https://www.redmine.org/boards/1/topics/46190

**Comment by electricnachus** [comment]
That's Great!!! thank very much Alex!!
(sorry for the delay, i will try it asap)
