### ISSUE TITLE
Add option to hide "project" in menu

### ISSUE THREAD

**Issue by EdenilsonF** [AlphaNodes/redmine_tweaks#34]
Hello, what steps do you follow to add the option to hide the "project" item in the menu?

**Comment by alexandermeindl** [comment]
Hi, redmine_tweaks does not hide a project item in menu. Which menu do you mean? (Top menu, project menu or application menu)

**Comment by EdenilsonF** [comment]
Hi, Top Menu. I would like to hide the "project" item from top_menu for users who are not authenticated.

**Comment by alexandermeindl** [comment]
This feature is not supported by Redmine Tweaks, sorry.

**Comment by EdenilsonF** [comment]
But is it possible to create this feature in Redmine Tweaks by editing the existing code?
