### ISSUE TITLE
You specified: deface (> 1.0.0) and deface (>= 0). Bundler cannot continue.

### ISSUE THREAD

**Issue by juxta73** [AlphaNodes/redmine_tweaks#39]
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `PluginGemfile`: You cannot specify the same gem twice with different version requirements.
You specified: deface (> 1.0.0) and deface (>= 0). Bundler cannot continue.

 #  from /var/www/redmine/plugins/redmine_tweaks/PluginGemfile:1
 #  -------------------------------------------
 >  gem 'deface'
 #  gem 'gemoji', '~> 3.0.0'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/www/redmine/Gemfile:118
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

my gems list

*** LOCAL GEMS ***

actionmailer (4.2.7.1)
actionpack (4.2.7.1)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.7.1)
activejob (4.2.7.1)
activemodel (4.2.7.1)
activerecord (4.2.7.1)
activesupport (4.2.7.1)
addressable (2.5.0)
arel (6.0.4)
bigdecimal (1.2.8)
builder (3.2.2)
bundler (1.13.7)
bundler-unload (1.0.2)
business_time (0.7.6)
climate_control (0.1.0)
cocaine (0.5.8)
coderay (1.1.1)
colorize (0.8.1)
concurrent-ruby (1.0.4)
css_parser (1.4.7)
deface (1.2.0, 1.1.0)
did_you_mean (1.0.0)
erubis (2.7.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
gemoji (3.0.0)
globalid (0.3.7)
hashie (3.4.6)
htmlentities (4.3.1)
i18n (0.7.0)
io-console (0.4.5)
jquery-rails (3.1.4)
json (1.8.3)
kaminari (1.0.0)
kaminari-actionview (1.0.0)
kaminari-activerecord (1.0.0)
kaminari-core (1.0.0)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.2)
mini_portile2 (2.1.0)
minitest (5.10.1, 5.8.5)
multi_json (1.12.1)
mysql2 (0.3.21)
net-ldap (0.12.1)
net-telnet (0.1.1)
nokogiri (1.6.8.1)
pandoc-ruby (2.0.1)
paperclip (4.2.4)
passenger (5.1.1)
polyglot (0.3.5)
power_assert (0.2.6)
protected_attributes (1.1.3)
psych (2.1.0)
public_suffix (2.0.4)
rack (2.0.1, 1.6.5)
rack-openid (1.4.2)
rack-raw-upload (1.1.1)
rack-test (0.6.3)
rails (4.2.7.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.7.1)
rainbow (2.2.2)
rake (12.0.0, 10.4.2)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdoc (4.2.1)
redcarpet (3.3.4)
request_store (1.0.5)
rmagick (2.16.0)
roadie (3.2.0)
roadie-rails (1.1.1)
ruby-openid (2.3.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.23)
sass-rails (5.0.6)
sprockets (3.7.1)
sprockets-rails (3.2.0)
test-unit (3.1.5)
thor (0.19.4)
thread_safe (0.3.5)
tilt (2.0.5)
tzinfo (1.2.2)

**Comment by alexandermeindl** [comment]
This plugin uses:

 gem 'deface'

If you use another plugin with an other Gem integration, this error occurs. In this case, you can only use plugins, which uses the same integration of the gem package.
